import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {ThemeRegistry} from "@/styles/ThemeRegistry";
import {StoreProvider} from "@/store/StoreProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <StoreProvider>
            <ThemeRegistry options={{key: 'mui-theme'}}>{children}</ThemeRegistry>
        </StoreProvider>
        </body>
        </html>
    )
}
